#ifndef __CPU_CPP__
#define __CPU_CPP__

#include "../include/cpu.h"
#include "../include/definitions.h"

void CPU::Reset()
{
	*(this) = CPU();
}

void CPU::Initialize(Logger *logger, MMU *mmu, PortManager *pm)
{
	this->logger = logger;
    this->mmu = mmu;
    this->pm = pm;
}

void CPU::NMI_request()
{
	NMI_requested = true;
}

void CPU::MI_request(bool cc)
{
	MI_requested = cc;
}

byte CPU::tick()
{
	if(not NMI_servising) {
		if(NMI_requested) {
			halt = false;
			NMI_servising = true;
			NMI_requested = false;
			FF1 = false;
			stackPush(registers.pc);
			registers.pc = 0x0066;
			return 11;
		} else if(MI_requested and FF1) {
			halt = false;
			FF1 = FF2 = false;
			MI_requested = false;
			stackPush(registers.pc);
			registers.pc = 0x0038;
			return 13;
		} else if(halt) return 4;
	} return (this->*opcodesTable[mmu->read(registers.pc++)])();
}

const opcode CPU::opcodesTable[256]
=
{
	&CPU::opcode0x00,
    &CPU::opcode0x01,
    &CPU::opcode0x02,
    &CPU::opcode0x03,
    &CPU::opcode0x04,
    &CPU::opcode0x05,
    &CPU::opcode0x06,
    &CPU::opcode0x07,
    &CPU::opcode0x08,
    &CPU::opcode0x09,
    &CPU::opcode0x0A,
    &CPU::opcode0x0B,
    &CPU::opcode0x0C,
    &CPU::opcode0x0D,
    &CPU::opcode0x0E,
    &CPU::opcode0x0F,
    &CPU::opcode0x10,
    &CPU::opcode0x11,
    &CPU::opcode0x12,
    &CPU::opcode0x13,
    &CPU::opcode0x14,
    &CPU::opcode0x15,
    &CPU::opcode0x16,
    &CPU::opcode0x17,
    &CPU::opcode0x18,
    &CPU::opcode0x19,
    &CPU::opcode0x1A,
    &CPU::opcode0x1B,
    &CPU::opcode0x1C,
    &CPU::opcode0x1D,
    &CPU::opcode0x1E,
    &CPU::opcode0x1F,
    &CPU::opcode0x20,
    &CPU::opcode0x21,
    &CPU::opcode0x22,
    &CPU::opcode0x23,
    &CPU::opcode0x24,
    &CPU::opcode0x25,
    &CPU::opcode0x26,
    &CPU::opcode0x27,
    &CPU::opcode0x28,
    &CPU::opcode0x29,
    &CPU::opcode0x2A,
    &CPU::opcode0x2B,
    &CPU::opcode0x2C,
    &CPU::opcode0x2D,
    &CPU::opcode0x2E,
    &CPU::opcode0x2F,
    &CPU::opcode0x30,
    &CPU::opcode0x31,
    &CPU::opcode0x32,
    &CPU::opcode0x33,
    &CPU::opcode0x34,
    &CPU::opcode0x35,
    &CPU::opcode0x36,
    &CPU::opcode0x37,
    &CPU::opcode0x38,
    &CPU::opcode0x39,
    &CPU::opcode0x3A,
    &CPU::opcode0x3B,
    &CPU::opcode0x3C,
    &CPU::opcode0x3D,
    &CPU::opcode0x3E,
    &CPU::opcode0x3F,
    &CPU::opcode0x40,
    &CPU::opcode0x41,
    &CPU::opcode0x42,
    &CPU::opcode0x43,
    &CPU::opcode0x44,
    &CPU::opcode0x45,
    &CPU::opcode0x46,
    &CPU::opcode0x47,
    &CPU::opcode0x48,
    &CPU::opcode0x49,
    &CPU::opcode0x4A,
    &CPU::opcode0x4B,
    &CPU::opcode0x4C,
    &CPU::opcode0x4D,
    &CPU::opcode0x4E,
    &CPU::opcode0x4F,
    &CPU::opcode0x50,
    &CPU::opcode0x51,
    &CPU::opcode0x52,
    &CPU::opcode0x53,
    &CPU::opcode0x54,
    &CPU::opcode0x55,
    &CPU::opcode0x56,
    &CPU::opcode0x57,
    &CPU::opcode0x58,
    &CPU::opcode0x59,
    &CPU::opcode0x5A,
    &CPU::opcode0x5B,
    &CPU::opcode0x5C,
    &CPU::opcode0x5D,
    &CPU::opcode0x5E,
    &CPU::opcode0x5F,
    &CPU::opcode0x60,
    &CPU::opcode0x61,
    &CPU::opcode0x62,
    &CPU::opcode0x63,
    &CPU::opcode0x64,
    &CPU::opcode0x65,
    &CPU::opcode0x66,
    &CPU::opcode0x67,
    &CPU::opcode0x68,
    &CPU::opcode0x69,
    &CPU::opcode0x6A,
    &CPU::opcode0x6B,
    &CPU::opcode0x6C,
    &CPU::opcode0x6D,
    &CPU::opcode0x6E,
    &CPU::opcode0x6F,
    &CPU::opcode0x70,
    &CPU::opcode0x71,
    &CPU::opcode0x72,
    &CPU::opcode0x73,
    &CPU::opcode0x74,
    &CPU::opcode0x75,
    &CPU::opcode0x76,
    &CPU::opcode0x77,
    &CPU::opcode0x78,
    &CPU::opcode0x79,
    &CPU::opcode0x7A,
    &CPU::opcode0x7B,
    &CPU::opcode0x7C,
    &CPU::opcode0x7D,
    &CPU::opcode0x7E,
    &CPU::opcode0x7F,
    &CPU::opcode0x80,
    &CPU::opcode0x81,
    &CPU::opcode0x82,
    &CPU::opcode0x83,
    &CPU::opcode0x84,
    &CPU::opcode0x85,
    &CPU::opcode0x86,
    &CPU::opcode0x87,
    &CPU::opcode0x88,
    &CPU::opcode0x89,
    &CPU::opcode0x8A,
    &CPU::opcode0x8B,
    &CPU::opcode0x8C,
    &CPU::opcode0x8D,
    &CPU::opcode0x8E,
    &CPU::opcode0x8F,
    &CPU::opcode0x90,
    &CPU::opcode0x91,
    &CPU::opcode0x92,
    &CPU::opcode0x93,
    &CPU::opcode0x94,
    &CPU::opcode0x95,
    &CPU::opcode0x96,
    &CPU::opcode0x97,
    &CPU::opcode0x98,
    &CPU::opcode0x99,
    &CPU::opcode0x9A,
    &CPU::opcode0x9B,
    &CPU::opcode0x9C,
    &CPU::opcode0x9D,
    &CPU::opcode0x9E,
    &CPU::opcode0x9F,
    &CPU::opcode0xA0,
    &CPU::opcode0xA1,
    &CPU::opcode0xA2,
    &CPU::opcode0xA3,
    &CPU::opcode0xA4,
    &CPU::opcode0xA5,
    &CPU::opcode0xA6,
    &CPU::opcode0xA7,
    &CPU::opcode0xA8,
    &CPU::opcode0xA9,
    &CPU::opcode0xAA,
    &CPU::opcode0xAB,
    &CPU::opcode0xAC,
    &CPU::opcode0xAD,
    &CPU::opcode0xAE,
    &CPU::opcode0xAF,
    &CPU::opcode0xB0,
    &CPU::opcode0xB1,
    &CPU::opcode0xB2,
    &CPU::opcode0xB3,
    &CPU::opcode0xB4,
    &CPU::opcode0xB5,
    &CPU::opcode0xB6,
    &CPU::opcode0xB7,
    &CPU::opcode0xB8,
    &CPU::opcode0xB9,
    &CPU::opcode0xBA,
    &CPU::opcode0xBB,
    &CPU::opcode0xBC,
    &CPU::opcode0xBD,
    &CPU::opcode0xBE,
    &CPU::opcode0xBF,
    &CPU::opcode0xC0,
    &CPU::opcode0xC1,
    &CPU::opcode0xC2,
    &CPU::opcode0xC3,
    &CPU::opcode0xC4,
    &CPU::opcode0xC5,
    &CPU::opcode0xC6,
    &CPU::opcode0xC7,
    &CPU::opcode0xC8,
    &CPU::opcode0xC9,
    &CPU::opcode0xCA,
    &CPU::opcode0xCB,
    &CPU::opcode0xCC,
    &CPU::opcode0xCD,
    &CPU::opcode0xCE,
    &CPU::opcode0xCF,
    &CPU::opcode0xD0,
    &CPU::opcode0xD1,
    &CPU::opcode0xD2,
    &CPU::opcode0xD3,
    &CPU::opcode0xD4,
    &CPU::opcode0xD5,
    &CPU::opcode0xD6,
    &CPU::opcode0xD7,
    &CPU::opcode0xD8,
    &CPU::opcode0xD9,
    &CPU::opcode0xDA,
    &CPU::opcode0xDB,
    &CPU::opcode0xDC,
    &CPU::opcode0xDD,
    &CPU::opcode0xDE,
    &CPU::opcode0xDF,
    &CPU::opcode0xE0,
    &CPU::opcode0xE1,
    &CPU::opcode0xE2,
    &CPU::opcode0xE3,
    &CPU::opcode0xE4,
    &CPU::opcode0xE5,
    &CPU::opcode0xE6,
    &CPU::opcode0xE7,
    &CPU::opcode0xE8,
    &CPU::opcode0xE9,
    &CPU::opcode0xEA,
    &CPU::opcode0xEB,
    &CPU::opcode0xEC,
    &CPU::opcode0xED,
    &CPU::opcode0xEE,
    &CPU::opcode0xEF,
    &CPU::opcode0xF0,
    &CPU::opcode0xF1,
    &CPU::opcode0xF2,
    &CPU::opcode0xF3,
    &CPU::opcode0xF4,
    &CPU::opcode0xF5,
    &CPU::opcode0xF6,
    &CPU::opcode0xF7,
    &CPU::opcode0xF8,
    &CPU::opcode0xF9,
    &CPU::opcode0xFA,
    &CPU::opcode0xFB,
    &CPU::opcode0xFC,
    &CPU::opcode0xFD,
    &CPU::opcode0xFE,
    &CPU::opcode0xFF
};

#endif